/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package reportes;

import controllers.CtrlListCarrera;
import controllers.CtrlReportStudentGrade;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.StudentGrade;

/**
 *
 * @author lnarvaezb
 */
public class RptMatriculaSemestre extends javax.swing.JInternalFrame {

    /**
     * Creates new form RptMatriculasSemestre
     */
    public RptMatriculaSemestre() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlContainer = new javax.swing.JPanel();
        jLblLogo = new javax.swing.JLabel();
        jLblActa = new javax.swing.JLabel();
        jLblCarrera = new javax.swing.JLabel();
        jLblFacultad = new javax.swing.JLabel();
        jCmbCarrera = new javax.swing.JComboBox<>();
        jScrTable = new javax.swing.JScrollPane();
        jTblReporte = new javax.swing.JTable();
        jBtnImprimir = new javax.swing.JButton();
        jBtnNuevo = new javax.swing.JButton();

        setClosable(true);
        setTitle("Reporte de Matriculas  por Carrera");
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setPreferredSize(new java.awt.Dimension(1024, 650));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPnlContainer.setBackground(new java.awt.Color(255, 255, 255));
        jPnlContainer.setPreferredSize(new java.awt.Dimension(1024, 620));

        jLblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportes/log_unan.png"))); // NOI18N

        jLblActa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblActa.setForeground(new java.awt.Color(0, 102, 153));
        jLblActa.setText("Acta de Matricula de Estudiante");

        jLblCarrera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblCarrera.setText("Carrera");

        jLblFacultad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblFacultad.setForeground(new java.awt.Color(0, 102, 153));
        jLblFacultad.setText("Facultad de Ciencias e Ingeniería");

        jCmbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        jCmbCarrera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CARNET", "NOMBRES", "APELLIDOS", "AÑO ACAD.", "CARRERA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTblReporte.setGridColor(new java.awt.Color(153, 153, 153));
        jTblReporte.setMinimumSize(new java.awt.Dimension(700, 120));
        jTblReporte.setRowHeight(30);
        jTblReporte.setShowHorizontalLines(true);
        jTblReporte.setShowVerticalLines(true);
        jScrTable.setViewportView(jTblReporte);
        if (jTblReporte.getColumnModel().getColumnCount() > 0) {
            jTblReporte.getColumnModel().getColumn(0).setResizable(false);
            jTblReporte.getColumnModel().getColumn(0).setPreferredWidth(110);
            jTblReporte.getColumnModel().getColumn(1).setResizable(false);
            jTblReporte.getColumnModel().getColumn(1).setPreferredWidth(180);
            jTblReporte.getColumnModel().getColumn(2).setResizable(false);
            jTblReporte.getColumnModel().getColumn(2).setPreferredWidth(180);
            jTblReporte.getColumnModel().getColumn(3).setResizable(false);
            jTblReporte.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTblReporte.getColumnModel().getColumn(4).setResizable(false);
            jTblReporte.getColumnModel().getColumn(4).setPreferredWidth(280);
        }

        jBtnImprimir.setText("Ver");
        jBtnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnImprimirActionPerformed(evt);
            }
        });

        jBtnNuevo.setText("Cargar Otro");
        jBtnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlContainerLayout = new javax.swing.GroupLayout(jPnlContainer);
        jPnlContainer.setLayout(jPnlContainerLayout);
        jPnlContainerLayout.setHorizontalGroup(
            jPnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlContainerLayout.createSequentialGroup()
                .addGroup(jPnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlContainerLayout.createSequentialGroup()
                        .addContainerGap(70, Short.MAX_VALUE)
                        .addGroup(jPnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPnlContainerLayout.createSequentialGroup()
                                .addComponent(jLblCarrera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnImprimir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnNuevo))
                            .addComponent(jScrTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPnlContainerLayout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addGroup(jPnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblFacultad)
                            .addComponent(jLblActa))
                        .addGap(6, 6, 6)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jPnlContainerLayout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(jLblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlContainerLayout.setVerticalGroup(
            jPnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblFacultad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblActa)
                .addGap(30, 30, 30)
                .addGroup(jPnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCarrera)
                    .addComponent(jCmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrTable, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnImprimirActionPerformed
        // TODO add your handling code here:
        //Definir el modelo de la tabla para pasar los datos = new DefaultTableModel();
        DefaultTableModel dModel = (DefaultTableModel)this.jTblReporte.getModel();
        //Recuperar el nombre de la carrera seleccionada en el Combo
        String carrera = this.jCmbCarrera.getSelectedItem().toString();        
        try {
            //Obtener el ArrayList con los elementos de la base de datos 
            for (StudentGrade sg: CtrlReportStudentGrade.listarStudentGrade(carrera))
            {
                dModel.addRow(new Object []{sg.getLicense(), sg.getStudentName()
                              , sg.getStudentLastName(),sg.getNivel()
                              , sg.getCareer()});                
            }//Fin de la instrucción for
            //Agregar los datos a la tabla por medio del modelo
                this.jTblReporte.setModel(dModel);
        }
        catch (java.lang.ClassNotFoundException | 
               java.lang.InstantiationException | 
               java.lang.IllegalAccessException |
               java.sql.SQLException ex) 
        {
          JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                  + "intentar \n generar el reporte solicitado \n " + ex.getMessage(), 
                  "Falla en la Generación de Reporte ", JOptionPane.ERROR_MESSAGE);
        }         
    }//GEN-LAST:event_jBtnImprimirActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        //Llenar el combo de selección de carrera con la información de la BD
        ArrayList<String> items = new ArrayList<>();
        
        try {
             items = CtrlListCarrera.leer();
             for (String it : items) {
                 this.jCmbCarrera.addItem(it);
            }//Fin de la instrucción for
        }
        catch (java.lang.ClassNotFoundException | 
               java.lang.InstantiationException |
               java.lang.IllegalAccessException |
               java.sql.SQLException ex )
            {
             JOptionPane.showMessageDialog(null, "Se ha producido una falla "
                     + "al intentar \n cargar datos de carreras" , 
                     "Falla de carga", JOptionPane.ERROR_MESSAGE);
            }  
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed
        // TODO add your handling code here:
        this.jCmbCarrera.setSelectedIndex(0);
        DefaultTableModel tabModel = (DefaultTableModel)this.jTblReporte.getModel();
        tabModel.setRowCount(0);
        this.jTblReporte.setModel(tabModel);
    }//GEN-LAST:event_jBtnNuevoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnImprimir;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JComboBox<String> jCmbCarrera;
    private javax.swing.JLabel jLblActa;
    private javax.swing.JLabel jLblCarrera;
    private javax.swing.JLabel jLblFacultad;
    private javax.swing.JLabel jLblLogo;
    private javax.swing.JPanel jPnlContainer;
    private javax.swing.JScrollPane jScrTable;
    private javax.swing.JTable jTblReporte;
    // End of variables declaration//GEN-END:variables
}
